my_website/my_website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from catalog.views import page_not_found

admin.site.site_header = "Панель администрирования BrandStack"
admin.site.index_title = "Интернет-магазин BrandStack"
admin.site.site_title = "BrandStack Admin"

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('catalog/', include('catalog.urls')),
    path('users/', include('users.urls', namespace='users')),
]

# Добавляем обработку медиа-файлов в режиме разработки
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = page_not_found

my_website/users/urls.py
from django.urls import path
from . import views


app_name = 'users'


urlpatterns = [ 
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', views.LogoutUserView.as_view(), name='logout'),
    path('register/', views.RegisterUserView.as_view(), name='register'),
    path('profile/', views.ProfileUserView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileEditUserView.as_view(), name='profile_edit'),
    path('password-change/', views.UserPasswordChangeView.as_view(),
        name='password_change'),
    path('password-change/done/', views.UserPasswordChangeDoneView.as_view(),
        name='password_change_done'),
    path('password-reset/', views.UserPasswordResetView.as_view(),
        name='password_reset'),
    path('password-reset/done/', views.UserPasswordResetDoneView.as_view(),
        name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('password-reset/complete/', views.UserPasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
]

my_website/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    photo = models.ImageField(
        upload_to="users/%Y/%m/%d/",
        blank=True,
        null=True,
        verbose_name="Фотография"
    )
    date_birth = models.DateTimeField(
        blank=True,
        null=True,
        verbose_name="Дата рождения"
    )

my_website/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth import get_user_model

import datetime


# Форма авторизации пользователя
class LoginUserForm(AuthenticationForm):
    username = forms.CharField(
        label='Имя пользователя (или E-mail)',
        widget=forms.TextInput(attrs={
            'class': 'form-input',
            'placeholder': 'Введите имя пользователя (или E-mail)'
        }),
    )

    password = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={
            'class': 'form-input',
            'placeholder': 'Введите пароль'
        }),
    )
    
    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


# Форма регистрации нового пользователя
class RegisterUserForm(UserCreationForm):
    
    username = forms.CharField(
        label='Имя пользователя',
        widget=forms.TextInput(attrs={
            'class': 'form-input',
            'placeholder': 'Введите имя пользователя'
        }),
    )

    password1 = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={
            'class': 'form-input',
            'placeholder': 'Введите пароль'
        }),
    )

    password2 = forms.CharField(
        label='Подтверждение пароля',
        widget=forms.PasswordInput(attrs={
            'class': 'form-input',
            'placeholder': 'Подвердите пароль'
        }),
    )

    photo = forms.ImageField(
        label='Фотография профиля',
        required=False,
        widget=forms.FileInput(attrs={
            'class': 'form-input'
        })
    )
    
    this_year = datetime.date.today().year
    max_year = this_year - 6
    date_birth = forms.DateField(
        label='Дата рождения',
        required=False,
        initial=datetime.date(max_year, datetime.date.today().month, datetime.date.today().day),
        widget=forms.SelectDateWidget(years=tuple(range(this_year-100, this_year-5)))
    )

    class Meta:
        model = get_user_model()
        fields = ['photo', 'username', 'email', 'first_name',
                  'last_name', 'date_birth', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'email': forms.TextInput(attrs={
                        'class': 'form-input',
                        'placeholder': 'Введите E-mail'
                     }),

            'first_name': forms.TextInput(attrs={
                            'class': 'form-input',
                            'placeholder': 'Введите имя'
                          }),

            'last_name': forms.TextInput(attrs={
                            'class': 'form-input',
                            'placeholder': 'Введите фамилию'
                         }),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Пользователь с таким E-mail уже существует.")
        return email


# Форма редактирования профиля пользователя
class ProfileUserForm(forms.ModelForm):
    
    username = forms.CharField(disabled=True, label='Имя пользователя', 
        widget=forms.TextInput(attrs={
            'class': 'form-input',
            'placeholder': 'Введите имя пользователя'
        }))

    email = forms.CharField(disabled=True, label='E-mail', 
        widget=forms.TextInput(attrs={
            'class': 'form-input',
            'placeholder': 'Введите E-mail'
        }))
    
    date_joined = forms.DateTimeField(
        disabled=True,
        label='Дата регистрации',
        widget=forms.DateInput(attrs={'class': 'form-input'}, format='%d.%m.%Y')
    )
    
    this_year = datetime.date.today().year
    date_birth = forms.DateField(
        label='Дата рождения',
        required=False,
        widget=forms.SelectDateWidget(years=tuple(range(this_year-100, this_year-5)))
    )
    
    photo = forms.ImageField(
        label='Фотография профиля',
        required=False,
        widget=forms.FileInput(attrs={'class': 'form-input'})
    )

    class Meta:
        model = get_user_model()
        fields = ['photo', 'username', 'email', 'first_name', 'last_name', 'date_birth', 'date_joined']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={
                            'class': 'form-input',
                            'placeholder': 'Введите имя'
                          }),

            'last_name': forms.TextInput(attrs={
                            'class': 'form-input',
                            'placeholder': 'Введите фамилию'
                         }),
        }


# Форма смены пароля пользователя
class UserPasswordChangeForm(PasswordChangeForm):

    old_password = forms.CharField(
        label='Текущий пароль',
        widget=forms.PasswordInput(attrs={
            'class': 'form-input',
            'placeholder': 'Введите текущий пароль'
        })
    )

    new_password1 = forms.CharField(
        label='Новый пароль',
        widget=forms.PasswordInput(attrs={
            'class': 'form-input',
            'placeholder': 'Введите новый пароль'
        })
    )

    new_password2 = forms.CharField(
        label='Подтверждение нового пароля',
        widget=forms.PasswordInput(attrs={
            'class': 'form-input',
            'placeholder': 'Введите новый пароль'
        })
    )

my_website/users/views.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, UpdateView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from django.conf import settings
from .forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm

# Create your views here.


class LoginUserView(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}
    
    def get_success_url(self):
        next_url = self.request.POST.get('next') or self.request.GET.get('next')
        if next_url:
            return next_url
        return reverse_lazy('homepage')


class LogoutUserView(LogoutView):
    next_page = reverse_lazy('homepage')


class RegisterUserView(CreateView):
    model = get_user_model()
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': "Регистрация"}
    success_url = reverse_lazy('users:login')


class ProfileUserView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = 'users/profile.html'
    context_object_name = 'user'
    
    def get_object(self, queryset=None):
        return self.request.user
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Профиль'
        context['default_photo'] = settings.DEFAULT_USER_PHOTO
        return context


class ProfileEditUserView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile_edit.html'
    
    def get_object(self, queryset=None):
        return self.request.user
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактирование профиля'
        context['default_photo'] = settings.DEFAULT_USER_PHOTO
        return context
    
    def get_success_url(self):
        return reverse_lazy('users:profile')


class UserPasswordChangeView(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy('users:password_change_done')
    template_name = 'users/password_change_form.html'
    extra_context = {'title': 'Смена пароля'}


class UserPasswordChangeDoneView(PasswordChangeDoneView):
    template_name = 'users/password_change_done.html'
    extra_context = {'title': 'Пароль изменен'}


class UserPasswordResetView(PasswordResetView):
    template_name = 'users/password_reset_form.html'
    email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    extra_context = {'title': 'Восстановление пароля'}


class UserPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'users/password_reset_done.html'
    extra_context = {'title': 'Восстановление пароля'}


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:password_reset_complete')
    extra_context = {'title': 'Восстановление пароля'}


class UserPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'users/password_reset_complete.html'
    extra_context = {'title': 'Пароль изменен'}

my_website/users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ title }}</h1>

<form method="post" class="user-form">
    {% csrf_token %}

    <div class="form-error">
        {{ form.non_field_errors }}
    </div>

    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</p>

        <div class="form-error">
            {{ f.errors }}
        </div>
    {% endfor %}

    <input type="hidden" name="next" value="{{ next }}" />
    
    <p><button type="submit">Войти</button></p>
</form>

<p><a href="{% url 'users:password_reset' %}">Восстановить пароль</a></p>

<p>Нет аккаунта? <a href="{% url 'users:register' %}">Зарегистрироваться</a></p>

{% endblock %}

my_website/users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ title }}</h1>

<p>Ваш пароль был успешно изменен.</p>

<div class="navigation">
    <a href="{% url 'users:profile' %}">❮ Вернуться в профиль</a>
</div>

{% endblock %}

my_website/users/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ title }}</h1>

<form method="post" class="user-form">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>

    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <div class="form-actions">
        <button type="submit">Сменить пароль</button>
        <a href="{% url 'users:profile' %}" class="btn-cancel">Отмена</a>
    </div>
</form>

{% endblock %}

my_website/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ title }}</h1>

<p>Ваш пароль был успешно изменен!</p>

<div class="navigation">
    <a href="{% url 'users:login' %}">Войти в профиль</a>
</div>

{% endblock %}

my_website/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ title }}</h1>

{% if validlink %}

    <form method="post" class="user-form">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        
        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}

        <div class="form-actions">
            <button type="submit">Сохранить</button>
            <a href="{% url 'users:login' %}" class="btn-cancel">Отмена</a>
        </div>
    </form>

{% else %}

    <p>Ссылка для восстановления пароля недействительна. Возможно, она уже была использована или срок её действия истёк.</p>
    <p>Пожалуйста, запросите новую ссылку для восстановления пароля.</p>

    <div class="navigation">
        <a href="{% url 'users:password_reset' %}">Запросить новую ссылку</a>
        <a href="{% url 'users:login' %}">❮ Вернуться к входу</a>
    </div>

{% endif %}

{% endblock %}

my_website/users/templates/users/password_reset_done.html
{% extends "base.html" %}

{% block content %}

<h1>{{ title }}</h1>

<p>Мы отправили инструкцию по восстановлению пароля на указанный Вами адрес электронной почты, если в системе существует учётная запись с таким адресом. Письмо должно прийти в ближайшее время.</p>

<p>Если письмо не пришло, убедитесь, что Вы ввели правильный адрес электронной почты и проверьте папку «Спам».</p>

<div class="navigation">
    <a href="{% url 'users:login' %}">❮ Вернуться к входу</a>
</div>

{% endblock %}

my_website/users/templates/users/password_reset_email.html
{% autoescape off %}
Здравствуйте!

Вы получили это письмо, потому что был отправлен запрос на восстановление пароля для Вашей учётной записи на сайте {{ site_name }}.

Чтобы установить новый пароль, перейдите по следующей ссылке:
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

Ваше имя пользователя (на случай, если Вы его забыли): {{ user.get_username }}

Если Вы не запрашивали сброс пароля, просто проигнорируйте это сообщение.

Спасибо, что пользуетесь нашим сервисом!

С уважением,
Команда {{ site_name }}
{% endautoescape %}

my_website/users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ title }}</h1>

<form method="post" class="user-form">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    
    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <div class="form-actions">
        <button type="submit">Восстановить по E-mail</button>
        <a href="{% url 'users:login' %}" class="btn-cancel">Назад</a>
    </div>
</form>

{% endblock %}

my_website/users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ title }}</h1>

<div class="profile-view">
    <div class="profile-photo-section">
        {% if user.photo %}
            <img src="{{ user.photo.url }}" alt="Фото профиля" class="profile-photo-img">
        {% else %}
            <img src="{{ default_photo }}" alt="Фото профиля" class="profile-photo-img">
        {% endif %}
    </div>
    
    <div class="profile-info">
        <div class="profile-info-item">
            <span class="profile-label">Имя пользователя:</span>
            <span class="profile-value">{{ user.username }}</span>
        </div>
        
        <div class="profile-info-item">
            <span class="profile-label">E-mail:</span>
            <span class="profile-value">{{ user.email }}</span>
        </div>
        
        {% if user.first_name %}
        <div class="profile-info-item">
            <span class="profile-label">Имя:</span>
            <span class="profile-value">{{ user.first_name }}</span>
        </div>
        {% endif %}
        
        {% if user.last_name %}
        <div class="profile-info-item">
            <span class="profile-label">Фамилия:</span>
            <span class="profile-value">{{ user.last_name }}</span>
        </div>
        {% endif %}
        
        {% if user.date_birth %}
        <div class="profile-info-item">
            <span class="profile-label">Дата рождения:</span>
            <span class="profile-value">{{ user.date_birth|date:"d.m.Y" }}</span>
        </div>
        {% endif %}
        
        <div class="profile-info-item">
            <span class="profile-label">Дата регистрации:</span>
            <span class="profile-value">{{ user.date_joined|date:"d.m.Y" }}</span>
        </div>
    </div>
    
    <div class="profile-actions">
        <a href="{% url 'users:profile_edit' %}" class="btn-edit">Редактировать профиль</a>
        <a href="{% url 'users:password_change' %}" class="btn-edit">Сменить пароль</a>
    </div>
    
</div>

{% endblock %}

my_website/users/templates/users/profile_edit.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ title }}</h1>

<form method="post" enctype="multipart/form-data" class="user-form">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    
    {% if user.photo %}
        <p class="profile-photo"><img src="{{ user.photo.url }}" alt="Фото профиля"></p>
    {% else %}
        <p class="profile-photo"><img src="{{ default_photo }}" alt="Фото профиля"></p>
    {% endif %}
    
    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <div class="form-actions">
        <button type="submit">Сохранить</button>
        <a href="{% url 'users:profile' %}" class="btn-cancel">Отмена</a>
    </div>
</form>

{% endblock %}

my_website/users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ title }}</h1>

<form method="post" enctype="multipart/form-data" class="user-form">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    <div class="form-error">{{ form.non_field_errors }}</div>

    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    
    <p><button type="submit">Создать аккаунт</button></p>
</form>

<p>Уже есть аккаунт? <a href="{% url 'users:login' %}">Войти</a></p>

{% endblock %}